version: "3.3"
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'abc123/'
      MYSQL_ROOT_PASSWORD: 'abc123/'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: